=== bcmoney/OpenRecommender/schema/XML/recommendations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="recommendations">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="recommendation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="recommendation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="image"/>
        <xs:element ref="link"/>
        <xs:element ref="description" />
      </xs:sequence>
	  <xs:attribute name="priority" use="optional" type="xs:nonNegativeInteger"/>
	  <xs:attribute name="taxonomy" use="optional" type="xs:string"/>
		<xs:attribute name="type" use="optional" type="xs:string"/>
		<xs:attribute name="subject" use="optional" type="xs:string"/>			
		<xs:attribute name="creator" use="optional" type="xs:string"/>
		<xs:attribute name="audience" use="optional" type="xs:string"/>	  
		<xs:attribute name="date" use="optional" type="xs:date"/>
		<xs:attribute name="time" use="optional" type="xs:time"/>	
		<xs:attribute name="identifier" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute name="duration" use="optional" type="xs:string"/>
      <xs:attribute name="playlist" use="optional" type="xs:string"/>
      <xs:attribute name="captions" use="optional" type="xs:anyURI"/>
      <xs:attribute name="subtitles" use="optional" type="xs:anyURI"/>
		<xs:attribute name="language" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:anyURI">
		  <xs:attribute name="camera" use="optional" type="xs:string"/>		
		  <xs:attribute name="thumb" use="optional" type="xs:string"/>
		  <xs:attribute name="gallery" use="optional" type="xs:string"/>		  
			<xs:attribute name="format" use="optional" type="xs:string"/>
			<xs:attribute name="creator" use="optional" type="xs:anyURI"/>         
			<xs:attribute name="date" use="optional" type="xs:date"/>
			<xs:attribute name="time" use="optional" type="xs:time"/>
			<xs:attribute name="publisher" use="optional" type="xs:anyURI"/>
			<xs:attribute name="rights" use="optional" type="xs:string"/>
			<xs:attribute name="rightsHolder" use="optional" type="xs:anyURI"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:anyURI">
          <xs:attribute name="proxy" use="optional" type="xs:anyURI"/>
          <xs:attribute name="download" use="optional" type="xs:anyURI"/>
		  <xs:attribute name="oembed" use="optional" type="xs:anyURI"/>
          <xs:attribute name="mobile" use="optional" type="xs:anyURI"/>
		  <xs:attribute name="mobilestream" use="optional" type="xs:anyURI"/>
		  <xs:attribute name="mobiledownload" use="optional" type="xs:anyURI"/>		  
			<xs:attribute name="format" use="optional" type="xs:string"/>
			<xs:attribute name="creator" use="optional" type="xs:string"/>
			<xs:attribute name="date" use="optional" type="xs:date"/>
			<xs:attribute name="time" use="optional" type="xs:time"/>
			<xs:attribute name="publisher" use="optional" type="xs:string"/>
			<xs:attribute name="rights" use="optional" type="xs:string"/>
			<xs:attribute name="rightsHolder" use="optional" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="description" use="optional">
    <xs:complexType mixed="true">
      <xs:simpleContent>
        <xs:extension base="xs:string">	
	      <xs:attribute name="rating" use="optional" type="xs:string"/>
          <xs:attribute name="review" use="optional" type="xs:string"/>
		    <xs:attribute name="language" use="optional" type="xs:NCName"/>
		    <xs:attribute name="creator" use="optional" type="xs:string"/>
		    <xs:attribute name="date" use="optional" type="xs:date"/>
        </xs:extension>
      </xs:simpleContent>			
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bcmoney/OpenRecommender/schema/XML/recommendations.xml
<?xml version="1.0" encoding="UTF-8"?><recommendations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openrecommender.org/schema/XML/recommendations.xsd" xmlns:dc="http://purl.org/dc/elements/1.1/">    <recommendation identifier="1" sender="bryan" receiver="JaySay" date="2008-07-04" time="15:37:11" priority="3" type="TV">        <title duration="24:08" language="EN" captions="http://captions.bcmoney-mobiletv.com/?v=361" subtitles="http://subtitles.bcmoney-mobiletv.com/?v=361" playlist="Best of MAD TV">MAD TV - Abercrombie Skits</title>             <image creator="http://ffmpeg.mplayerhq.hu/" publisher="BCmoney MobileTV" format="image/jpg" rights="Public Domain" rightsHolder="NBC">http://bcmoney-mobiletv.com/thumb/361.jpg</image>        <link shortlink="http://tinyurl.com/5868du" location="http://bcmoney-mobiletv.com/flvideo/12105501011832425203.flv" mobile="http://bcmoney-mobiletv.com/m/m_info.php?v=361" mobiledownload="http://bcmoney-mobiletv.com/video/12105501011832425203.flv.mp4" mobilestream="rtsp://bcmoney-mobiletv.com/flvideo/12105501011832425203.flv.3gp" format="video/x-flv" creator="MAD TV" publisher="BCmoney MobileTV" rights="Preview only (Full Programme access limited to Members)" rightsHolder="FOX" oembed="http://bcmoney-mobiletv.com/361/oembed/">http://bcmoney-mobiletv.com/view/361/mad-tv-abercrombie-skits/</link>        <description rating="5" review="I laughed, I cried, I hurled">This is the best video making fun of Abercrombie and Fitch I've EVER seen!</description>    </recommendation>    <recommendation identifier="2" sender="DCworks" receiver="vltz" date="2008-08-07" time="11:58:11" priority="4" type="PC">        <title duration="57345" language="EN" captions="http://captions.bcmoney-mobiletv.com/?v=278" subtitles="http://subtitles.bcmoney-mobiletv.com/?v=278" playlist="Unfreakinbelievable Nature">Elephant Paints Self Portrait</title>             <image creator="http://ffmpeg.mplayerhq.hu/" publisher="BCmoney MobileTV" format="image/jpg" rights="Public Domain" rightsHolder="Animal Planet">http://bcmoney-mobiletv.com/thumb/1_278.jpg</image>        <link shortlink="http://tinyurl.com/5rqlad" location="http://bcmoney-mobiletv.com/flvideo/12070374021868154264.flv" mobile="http://bcmoney-mobiletv.com/m/m_info.php?v=278" mobiledownload="http://bcmoney-mobiletv.com/video/12070374021868154264.flv.mp4" mobilestream="rtsp://bcmoney-mobiletv.com/video/12070374021868154264.flv.3gp" format="video/x-flv" creator="Animal Planet" publisher="BCmoney MobileTV" rights="Public Domain" rightsHolder="Animal Planet" oembed="http://bcmoney-mobiletv.com/278/oembed/">http://bcmoney-mobiletv.com/view/278/elephant-paints-self-portrait/</link>        <description rating="5" review="This is really amazing... but is it real? Your call" subject="northern  Thailand  elephant  paints  painting  selfportrait  amazing  Pachyderm  Picasso  elephants  reserve">A Burmese Asian elephant (elephas maximus) named Dot paints her own self-portrait in this amazing video shot in the North of Thailand just outside Chiangmai, near the border of Myanmar.</description>    </recommendation></recommendations>
